{{- if .Values.openshift }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "citrix-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
{{- if .Values.openshift }}
     router: {{ include "citrix-ingress-controller.fullname" . }}
{{- else }}
    matchLabels:
      app: {{ include "citrix-ingress-controller.fullname" . }}
{{- end }}
  replicas: 1
{{- if .Values.openshift }}
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 0
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
{{- end }}
  template:
    metadata:
      name: cic
      labels:
{{- if .Values.openshift }}
        router: {{ include "citrix-ingress-controller.fullname" . }}
{{- else }}
        app: {{ include "citrix-ingress-controller.fullname" . }}
{{- end }}
{{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "citrix-ingress-controller.serviceAccountName" . }}
      containers:
      - name: cic
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
          - --configmap
            {{ .Release.Namespace }}/{{ include "cicconfigmap.fullname" . }}
{{- if .Values.defaultSSLCertSecret }}
          - --default-ssl-certificate
            {{ .Release.Namespace }}/{{ .Values.defaultSSLCertSecret }}
{{- end }}
{{- if .Values.ingressClass }}
          - --ingress-classes
{{- range .Values.ingressClass}}
            {{.}}
{{- end }}
{{- end }}
{{- if .Values.serviceClass }}
          - --service-classes
{{- range .Values.serviceClass}}
            {{.}}
{{- end }}
{{- end }}
          - --feature-node-watch
            {{ .Values.nodeWatch }}
          - --enable-cnc-pbr
            {{ .Values.cncPbr }}
{{- if .Values.ipam }}
          - --ipam
            citrix-ipam-controller
{{- end }}
{{- if .Values.disableAPIServerCertVerify }}
          - --disable-apiserver-cert-verify
            {{ .Values.disableAPIServerCertVerify }}
{{- end }}
{{- if .Values.updateIngressStatus }}
          - --update-ingress-status
            yes
{{- end }}
        env:
        - name: "NS_IP"
          value: "{{ .Values.nsIP }}"
{{- if .Values.nsVIP }}
        - name: "NS_VIP"
          value: "{{ .Values.nsVIP }}"
{{- end }}
{{- if .Values.nitroReadTimeout }}
        - name: "NS_NITRO_READ_TIMEOUT"
          value: "{{ .Values.nitroReadTimeout }}"
{{- end }}
        - name: "NS_USER"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.adcCredentialSecret }}
              key: username
        - name: "NS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.adcCredentialSecret }}
              key: password
        - name: "EULA"
          value: "{{ .Values.license.accept }}"
{{- if and .Values.openshift .Values.routeLabels }}
        - name: "ROUTE_LABELS"
          value: {{ .Values.routeLabels | quote}}
{{- end }}
{{- if and .Values.openshift .Values.namespaceLabels }}
        - name: "NAMESPACE_LABELS"
          value: {{ .Values.namespaceLabels | quote }}
{{- end }}
        - name: "NS_APPS_NAME_PREFIX"
          value: {{ .Values.entityPrefix | default "k8s"}}
{{- if .Values.kubernetesURL }}
        - name: "kubernetes_url"
          value: "{{ .Values.kubernetesURL }}"
{{- end }}
{{- if .Values.clusterName }}
        - name: "CLUSTER_NAME"
          value: "{{ .Values.clusterName }}"
{{- end }}
{{- if .Values.logProxy }}
        - name: "NS_LOGPROXY"
          value: "{{ .Values.logProxy }}"
{{- end }}
{{- if .Values.disableOpenshiftRoutes }}
        - name: "DISABLE_OPENSHIFT_ROUTES"
          value: "{{ .Values.disableOpenshiftRoutes }}"
{{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.exporter.required }}
      - name: exporter
        image: "{{ .Values.exporter.image }}"
        imagePullPolicy: {{ .Values.exporter.pullPolicy }}
        args:
          - "--target-nsip={{ .Values.nsIP }}"
          - "--port={{ .Values.exporter.ports.containerPort }}"
        volumeMounts:
          - name: nslogin
            mountPath: "/mnt/nslogin"
            readOnly: true
        securityContext:
          readOnlyRootFilesystem: true
        resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
      volumes:
      - name: nslogin
        secret:
          secretName: {{ .Values.adcCredentialSecret }}
{{- end }}
{{- if and .Values.nodeSelector.key .Values.nodeSelector.value }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}

---

{{- if .Values.exporter.required }}


apiVersion: v1
kind: Service
metadata:
   name: {{ include "exporter.fullname" . }}
   labels:
     app: {{ include "exporter.fullname" . }}
     service-type: {{ include "servicemonitorlabel" . }}
spec:
   type: ClusterIP
   ports:
   - port: {{ .Values.exporter.ports.containerPort }}
     targetPort: {{ .Values.exporter.ports.containerPort }}
     name: exporter-port
   selector:
{{- if .Values.openshift }}
     router: {{ include "citrix-ingress-controller.fullname" . }}
{{- else }}
     app: {{ include "citrix-ingress-controller.fullname" . }}
{{- end }}

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "servicemonitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    servicemonitor: citrix-adc
spec:
  endpoints:
  - interval: 30s
    port: exporter-port
  selector:
    matchLabels:
      service-type: {{ include "servicemonitorlabel" . }}
  namespaceSelector:
    matchNames:
    - monitoring
    - default
    - {{ .Release.Namespace }}

{{- end }}
