apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adcCredentialSecret }}
  namespace:  {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.adc.username | b64enc | quote }}
  password: {{ .Values.adc.password | b64enc | quote }}
